/**
 * items.js draws the things that live inside a band: text boxes and tables.
 *
 * Split out of render.js because the designer canvas needs exactly this and
 * nothing more. The preview wraps these in anchored, paginated bands; the
 * designer wraps them in band zones on a single unpaginated page. Spec 5.2 asks
 * for one drawing path so that what is designed looks like what is printed -
 * two paths drift, and the drift is always found by a user rather than a test.
 *
 * Every element carries data-item-id and data-item-type. The preview ignores
 * them; the designer uses them to take a pointer event back to a layout item
 * without maintaining a parallel element map that can fall out of step.
 */


/** items are placed against the band box, which the caller has made relative */
export const position = (p) => `position:absolute;top:${px(p?.y)}px;left:${px(p?.x)}px;`;


/**
 * A number on its way into a style attribute.
 *
 * A layout is JSON, and JSON says nothing about what type a field holds: a `w`
 * that arrived as a string writes `width:undefinedpx` at best and closes the
 * attribute at worst. Anything that is not a finite number is the fallback.
 *
 * @param {*} value
 * @param {number} [fallback]
 * @returns {number}
 */
export function px(value, fallback = 0) {
    const n = Number(value);
    return Number.isFinite(n) ? n : fallback;
}


/**
 * A style *value* on its way into a `style="..."` attribute.
 *
 * `esc` is for text between tags; this is for the other half. Item text comes
 * from the host's data and is escaped on the way in, but a colour, a font
 * family or a background comes from the layout - and a layout is a file, which
 * an application may well let its own users author. Written raw, a colour of
 * `red" onmouseover="alert(1)` closed the attribute and put a live event
 * handler on the element.
 *
 * Removed rather than entity-escaped: `&quot;` inside a style attribute is a
 * quote again by the time CSS parses it, so escaping would move the hole
 * rather than close it. None of these characters appear in a colour, a length
 * or a font stack, so nothing legitimate is lost - and `;` and `{}` go too, so
 * a value cannot append a declaration of its own to the ones around it.
 *
 * Brackets stay, because `rgb(...)` and `linear-gradient(...)` are ordinary
 * things to write in a layout. `url(` alone does not: it is the one CSS
 * function that fetches, and a report that quietly calls home when it is
 * opened is not a report anybody asked for.
 *
 * @param {*} value
 * @param {string} [fallback] what an empty or absent value becomes
 * @returns {string}
 */
export function css(value, fallback = '') {
    if (value == null) return fallback;

    const clean = String(value)
        .replace(/[<>"'`&;{}\\]/g, '')
        .replace(/url\s*\(/gi, '')
        .replace(/\s+/g, ' ')
        .trim();

    return clean === '' ? fallback : clean;
}


/**
 * Everything that reaches the page came from user data, so it is escaped on the
 * way into the markup. Without this a value like "<script>" is executed rather
 * than printed.
 * @param {*} value
 * @returns {string}
 */
export function esc(value) {
    if (value == null) return '';
    return String(value)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}


/**
 * Draws every item in a band, in layout order.
 * @param {object[]} list the band's items
 * @returns {string} markup
 */
export function items(list) {
    return (list || []).map(i => {
        switch (i.type) {
            case "text":
                return text(i);
            case "table":
                return table(i)
            case "line":
                return line(i)
            case "box":
                return box(i)
            default:
                console.warn(`Unknown item type "${i?.type}"; it is not drawn.`);
                return '';
        }
    }).join("");
}


function text(i) {
    /**
     * `?? {}` the way box and line have always had it. A text item with no
     * style block is a layout validateLayout accepts - it asks for a style to
     * be an object *if there is one* - and reading straight through it threw a
     * TypeError out of the renderer for a layout the validator had just called
     * fine. Written by hand or generated by an API rather than drawn, but the
     * two halves of the package have to agree about what they accept.
     */
    const style = i.style ?? {};

    return `
    <p id="${esc(i.id)}" style="
    width:${px(i.w)}px;
    height:${px(i.h)}px;
    ${position(i)}
    font-size:${px(style.fontSize, 12)}px;
    font-family:${css(style.fontFamily, 'inherit')};
    font-weight:${css(style.fontWeight, 'normal')};
    font-style:${css(style.fontStyle, 'normal')};
    text-align:${css(style.align, 'left')};
    color:${css(style.color, 'inherit')};
    " data-item-id="${esc(i.id)}" data-item-type="text">${esc(i.text)}</p>
    `
}


/**
 * A rectangle: a rule bent round four sides, with an optional fill.
 *
 * `box-sizing: border-box` in the stylesheet, so `w` and `h` are the outside of
 * the box however thick its border - which is what the designer draws round it
 * and what the engine paginated against. A border that added to them would put
 * the two a few pixels apart at every thickness.
 *
 * Drawn before the items above it, because paginate orders a band by `y` and a
 * backdrop is placed at the top of what it sits behind.
 */
function box(i) {
    const style = i.style ?? {};
    const width = Math.max(0, Number(style.borderWidth ?? 1)) || 1;

    const pen = RULE_STYLES.includes(style.borderStyle) ? style.borderStyle : 'solid';
    const border = `${width}px ${pen} ${css(style.borderColor, '#000000')}`;

    const radius = Math.max(0, Number(style.radius ?? 0)) || 0;

    const background = css(style.background);

    return `
    <div id="${esc(i.id)}" class="box" style="
    width:${px(i.w)}px;
    height:${px(i.h)}px;
    ${position(i)}
    border:${border};
    ${radius ? `border-radius:${radius}px;` : ''}
    ${background ? `background:${background};` : ''}
    " data-item-id="${esc(i.id)}" data-item-type="box"></div>
    `
}


/**
 * The pen a line is drawn with, as one CSS border shorthand.
 *
 * `lineStyle` is whitelisted rather than passed through, the way tableRule
 * already whitelists the grid's: the designer canvas draws straight from the
 * layout without asking the validator, so a value it does not recognise should
 * fall back to a rule rather than land in a style attribute.
 */
function stroke(style) {
    const thickness = Math.max(0, Number(style?.thickness ?? 1)) || 1;
    const pen = LINE_STYLES.includes(style?.lineStyle) ? style.lineStyle : 'solid';

    return `${thickness}px ${pen} ${css(style?.color, '#000000')}`;
}


/**
 * A rule, drawn down the middle of the item's box.
 *
 * The box is not the rule: a 1px hairline that *was* its box would be a 1px
 * target in the designer, and an item nobody can click is an item nobody can
 * edit. So the box is whatever `h` (or `w`, running vertically) says, and the
 * rule sits centred inside it - which is also where an eye expects a rule that
 * separates one thing from another to fall.
 *
 * The border goes on the inner span rather than the box, so that `w` and `h`
 * keep meaning what they mean for every other item.
 */
function line(i) {
    const vertical = i.orientation === 'vertical';
    const pen = stroke(i.style);

    return `
    <div id="${esc(i.id)}" class="line${vertical ? ' is-vertical' : ''}" style="
    width:${px(i.w)}px;
    height:${px(i.h)}px;
    ${position(i)}
    " data-item-id="${esc(i.id)}" data-item-type="line"><span class="line-mark"
        style="${vertical ? `border-left:${pen}` : `border-top:${pen}`}"></span></div>
    `
}


/** what a rule may be drawn in; anything else is not a rule */
const LINE_STYLES = ['solid', 'dashed', 'dotted', 'double'];

/** a table's grid may also be drawn in nothing at all */
const RULE_STYLES = [...LINE_STYLES, 'none'];


/**
 * The widest rule a table can be drawn with and still measure what it declares.
 *
 * .cell is box-sizing: border-box with a fixed height, so a rule is drawn
 * inside the row rather than added to it - until the two rules of a cell are
 * together taller than the row, at which point the cell has to grow and the
 * table stops being headerHeight + rows x rowHeight. Half the shallowest row
 * is the point where that starts, so that is the limit.
 *
 * @param {object} item the table
 * @returns {number} pixels
 */
function maxRuleWidth(item) {
    const rowHeight = item.rowHeight ?? 0;
    const headerHeight = item.showHeader ? (item.headerHeight ?? rowHeight) : rowHeight;

    const shallowest = Math.min(rowHeight || Infinity, headerHeight || Infinity);

    return Number.isFinite(shallowest) ? Math.max(1, Math.floor(shallowest / 2)) : 1;
}


/**
 * A table's grid, as custom properties on the table itself.
 *
 * Set here and read by .cell rather than written onto every cell: a five
 * hundred row table has fifteen hundred cells, and the same border string
 * repeated that many times is markup nobody needs to send. Custom properties
 * inherit, so one declaration on the table reaches all of them.
 *
 * Only what the table actually declares is emitted, so a table that says
 * nothing keeps taking its colour from the stylesheet's own variable.
 *
 * @param {object} item the table
 * @returns {string} css declarations, or empty
 */
function tableRule(item) {
    const style = item.style ?? {};
    const out = [];

    /**
     * Whitelisted rather than passed through: the designer canvas draws
     * straight from the layout without asking the validator, and a border style
     * it does not recognise should fall back to the stylesheet rather than land
     * in a style attribute.
     */
    if (RULE_STYLES.includes(style.borderStyle)) {
        out.push(`--rs-rule-style:${style.borderStyle}`);
    }

    if (style.borderColor) out.push(`--rs-rule-color:${css(style.borderColor)}`);

    /**
     * The header's own colours, set here for the same reason the grid is: they
     * belong to every `th` in the table, and a table that says nothing about
     * them keeps taking the stylesheet's.
     */
    if (style.headerBackground) {
        out.push(`--rs-head-bg:${css(style.headerBackground)}`);
    }

    if (style.headerColor) out.push(`--rs-head-color:${css(style.headerColor)}`);

    /**
     * The cell font, which used to go nowhere at all: the rail offered a size
     * and a colour, report.css hard-coded 12px, and the two never met. It
     * matters more than it looks - the engine wraps a cell against this font,
     * so a table drawn in one and measured in another paginates to a row count
     * it does not print.
     */
    if (style.fontFamily) out.push(`--rs-cell-family:${css(style.fontFamily)}`);

    const size = Number(style.fontSize);
    if (Number.isFinite(size) && size > 0) out.push(`--rs-cell-size:${size}px`);

    if (style.color) out.push(`--rs-cell-color:${css(style.color)}`);

    /** one line and an ellipsis, for a column of figures that must not wrap */
    if (item.wrap === false) out.push('--rs-cell-wrap:nowrap');

    /**
     * Clamped rather than trusted: the rail will not offer a width past this,
     * but a hand-written layout can, and a rule that outgrows its row would
     * quietly undo the arithmetic pagination was done with.
     */
    const width = Number(style.borderWidth);

    if (Number.isFinite(width) && width > 0) {
        out.push(`--rs-rule-width:${Math.min(width, maxRuleWidth(item))}px`);
    }

    return out.length ? `${out.join(';')};` : '';
}


function table(i) {
    return `
    <table id="${esc(i.id)}" style="width:${px(i.w)}px;height:${px(i.measuredHeight)}px;${position(i)}${tableRule(i)}" data-item-id="${esc(i.id)}" data-item-type="table">
        ${i.groups ? groupedBody(i) : flatBody(i)}
    </table>
    `
}


/**
 * A cell's content, in a box of exactly the row's height.
 *
 * `height` on a `<tr>` is a minimum, not a height: a cell whose padding and
 * line box need more than that makes the row taller, and the table then outgrows
 * the `headerHeight + rows x rowHeight` the engine paginated against. A few
 * pixels a row is invisible until the fortieth row has pushed the detail band
 * over the page footer. So the padding lives on a box of a known height inside
 * the cell, and the cell itself adds nothing.
 *
 * @param {number} height the row height the engine budgeted
 * @param {string} align the column's text alignment
 * @param {*} value what the cell shows
 * @returns {string} markup
 */
function cell(height, align, value) {
    return `<div class="cell" style="height:${px(height)}px;text-align:${css(align, 'left')}">` +
        `${esc(value)}</div>`;
}


/** the column header row, shared by both table shapes */
function columnHeader(i) {
    /** what measure.js budgeted, which is taller than declared if a label wrapped */
    const height = i.headerMeasured ?? i.headerHeight ?? i.rowHeight;

    return `<thead>
        <tr style="height:${px(height)}px">
        ${i.columns.map(c => `<th style="width:${px(c.width)}px;">${cell(height, c.align, c.label)}</th>`).join("")}
        </tr>
    </thead>`;
}


/**
 * @param {object} i the table
 * @param {object[]} rows
 * @param {number[]} [heights] one per row, from measure.js; absent on the
 *   designer canvas, where nothing has been measured and every row is its
 *   declared height
 */
function dataRows(i, rows, heights) {
    return (rows || []).map((r, n) => {
        const height = heights?.[n] ?? i.rowHeight;

        return `<tr style="height:${px(height)}px">
        ${i.columns.map(c => `<td style="width:${px(c.width)}px;">${cell(height, c.align, r[c.field])}</td>`).join("")}
        </tr>`;
    }).join("");
}


/**
 * A group band is a designed band with absolutely positioned items, so it is
 * dropped into a full-width cell that recreates the band box inside the table.
 */
function groupBandRow(band, colSpan, cls) {
    if (!band) return '';
    const height = band.measuredHeight > 0 ? band.measuredHeight : (band.height ?? 0);
    return `<tr class="${cls}">
        <td colspan="${colSpan}" class="group-band-cell">
            <div class="band" style="position:relative;height:${px(height)}px">${items(band.items)}</div>
        </td>
    </tr>`;
}


function flatBody(i) {
    return `
        ${i.showHeader ? columnHeader(i) : ""}
        <tbody>
            ${dataRows(i, i.row, i.rowHeights)}
        </tbody>
    `;
}


/**
 * One tbody per group fragment, so a group that survives a page break keeps its
 * header on the next page and only prints its footer on the fragment that ends it.
 */
function groupedBody(i) {
    const colSpan = i.columns.length;

    return i.groups.map(g => `
        ${g.showHeader && i.showHeader ? columnHeader(i) : ""}
        <tbody>
            ${groupBandRow(g.headerBand, colSpan, "group-header")}
            ${dataRows(i, g.rows, g.rowHeights)}
            ${g.showFooter ? groupBandRow(g.footerBand, colSpan, "group-footer") : ""}
        </tbody>
    `).join("");
}
